// Generated file. DO NOT EDIT MANUALLY.
// Generated by supabase_codegen (4.0.0-alpha.1)

/// User Status Enum
enum UserStatus {
  /// active
  active,

  /// inactive
  inactive,
}

// Date: 2025-12-09 14:05:05.178011
