import 'package:supabase_codegen/src/generator/generator.dart';

/// Test [FieldNameTypeMap]
const FieldNameTypeMap testFieldNameTypeMap = {
  'isNotNullable': (
    dartType: 'String',
    isNullable: false,
    hasDefault: false,
    defaultValue: null,
    columnName: 'is_not_nullable',
    isArray: false,
    isEnum: false,
  ),
  'id': (
    dartType: 'String',
    isNullable: true,
    hasDefault: true,
    defaultValue: null,
    columnName: 'id',
    isArray: false,
    isEnum: false,
  ),
  'createdAt': (
    dartType: 'DateTime',
    isNullable: true,
    hasDefault: true,
    defaultValue: null,
    columnName: 'created_at',
    isArray: false,
    isEnum: false,
  ),
  'isNullable': (
    dartType: 'String',
    isNullable: true,
    hasDefault: false,
    defaultValue: null,
    columnName: 'is_nullable',
    isArray: false,
    isEnum: false,
  ),
  'isArray': (
    dartType: 'List<String>',
    isNullable: true,
    hasDefault: false,
    defaultValue: null,
    columnName: 'is_array',
    isArray: true,
    isEnum: false,
  ),
  'isInt': (
    dartType: 'int',
    isNullable: true,
    hasDefault: false,
    defaultValue: null,
    columnName: 'is_int',
    isArray: false,
    isEnum: false,
  ),
  'isDouble': (
    dartType: 'double',
    isNullable: true,
    hasDefault: false,
    defaultValue: null,
    columnName: 'is_double',
    isArray: false,
    isEnum: false,
  ),
  'isBool': (
    dartType: 'bool',
    isNullable: true,
    hasDefault: false,
    defaultValue: null,
    columnName: 'is_bool',
    isArray: false,
    isEnum: false,
  ),
  'isJson': (
    dartType: 'dynamic',
    isNullable: true,
    hasDefault: false,
    defaultValue: null,
    columnName: 'is_json',
    isArray: false,
    isEnum: false,
  ),
  'status': (
    dartType: 'Status',
    isNullable: true,
    hasDefault: false,
    defaultValue: null,
    columnName: 'status',
    isArray: false,
    isEnum: true,
  ),
  'isDynamic': (
    dartType: 'dynamic',
    isNullable: true,
    hasDefault: false,
    defaultValue: null,
    columnName: 'is_dynamic',
    isArray: false,
    isEnum: false,
  ),
};

/// Test [FieldNameTypeMap] entries
final testFieldNameTypeMapEntries = testFieldNameTypeMap.entries.toList();
