name: supabase_codegen
description: A codegen library that grabs and generates classes from Supabase tables and enums in Dart.
homepage: https://github.com/Khuwn-Soulutions/supabase_codegen
version: 2.0.0
repository: https://github.com/Khuwn-Soulutions/supabase_codegen
resolution: workspace

environment:
  sdk: ^3.5.0

dependencies:
  args: ^2.7.0
  change_case: ^2.2.0
  collection: ^1.19.1
  dcli: ^7.0.5
  dotenv: ^4.2.0
  http: ^1.5.0
  latlng: ^2.0.7
  logger: ^2.6.1
  meta: ^1.16.0
  mock_supabase_http_client: ^0.0.3+2
  path: ^1.9.1
  quiver: ^3.2.2
  supabase: ^2.9.1
  yaml: ^3.1.3

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.15
  test_badge_gen: ^0.0.2
  very_good_analysis: ^9.0.0

executables:
  generate_types:
  add_codegen_functions:
  init:
