// Generated file. DO NOT EDIT MANUALLY.
// Generated by supabase_codegen (4.0.0-alpha.1)

import 'package:supabase_codegen/supabase_codegen.dart';

/// Users Table
class UsersTable extends SupabaseTable<UsersRow> {
  /// Table Name
  @override
  String get tableName => 'users';

  /// Create a [UsersRow] from the [data] provided
  @override
  UsersRow createRow(Map<String, dynamic> data) => UsersRow.fromJson(data);
}

/// Users constructor
class UsersRow extends SupabaseDataRow {
  /// Users Row
  UsersRow({
    required int id,
    String? name,
    DateTime? createdAt,
    List<String>? tags,
  }) : super({
         idField: supaSerialize(id),
         if (name != null) nameField: supaSerialize(name),
         if (createdAt != null) createdAtField: supaSerialize(createdAt),
         if (tags != null) tagsField: supaSerialize(tags),
       });

  /// Users default constructor
  const UsersRow._(super.data);

  /// Create [UsersRow] from a [data] map
  factory UsersRow.fromJson(Map<String, dynamic> data) =>
      UsersRow._(data.cleaned);

  /// Get the Json representation of the Users row
  Map<String, dynamic> toJson() => data;

  /// Get the [SupabaseTable] for this row
  @override
  SupabaseTable get table => UsersTable();

  /// Id column name (id)
  static const String idField = 'id';

  /// Id
  int get id => getField<int>(idField)!;
  set id(int value) => setField<int>(idField, value);

  /// Name column name (name)
  static const String nameField = 'name';

  /// Name
  String get name => getField<String>(nameField, defaultValue: 'some default')!;
  set name(String value) => setField<String>(nameField, value);

  /// Created At column name (created_at)
  static const String createdAtField = 'created_at';

  /// Created At
  DateTime get createdAt =>
      getField<DateTime>(createdAtField, defaultValue: DateTime.now())!;
  set createdAt(DateTime value) => setField<DateTime>(createdAtField, value);

  /// Tags column name (tags)
  static const String tagsField = 'tags';

  /// Tags
  List<String> get tags => getListField<String>(tagsField);
  set tags(List<String>? value) => setListField<String>(tagsField, value);

  /// Make a copy of the current [UsersRow]
  /// overriding the provided fields
  UsersRow copyWith({
    int? id,
    String? name,
    DateTime? createdAt,
    List<String>? tags,
  }) => UsersRow.fromJson({
    idField: supaSerialize(id) ?? data[idField],
    nameField: supaSerialize(name) ?? data[nameField],
    createdAtField: supaSerialize(createdAt) ?? data[createdAtField],
    tagsField: supaSerialize(tags) ?? data[tagsField],
  });
}
