// Generated file. DO NOT EDIT MANUALLY.
// Generated by supabase_codegen (4.0.0-alpha.1)
export 'enums/_enums.dart';
export 'rpcs/_rpcs.dart';
export 'tables/_tables.dart';

// Date: 2025-12-09 14:05:05.178011
