import 'dart:async';

import 'package:meta/meta.dart';
import 'package:supabase/supabase.dart' show SupabaseClient;

/// Supabase Codegen Client
abstract class SupabaseCodegenClientBase {
  /// Default env path
  final String defaultEnvPath = '';

  /// Client type
  @visibleForTesting
  String platform = '';

  /// Are we running in a test environment
  @visibleForTesting
  bool isRunningInTest = false;

  /// Cached client
  @visibleForTesting
  SupabaseClient? supabaseClient;

  /// Set the [supabaseClient] to be used by classes generated by the package
  SupabaseClient setClient(SupabaseClient client);

  /// Create the supabase client with the provided [url] and [key]
  FutureOr<SupabaseClient> createClient(String url, String key);

  /// Load the supabase client using environment variables
  @visibleForTesting
  FutureOr<SupabaseClient> loadClientFromEnv([String? envPath]);

  /// Load the supabase client
  SupabaseClient loadSupabaseClient([String? envPath]);

  /// Load the mock supabase client
  @visibleForTesting
  FutureOr<SupabaseClient> loadMockSupabaseClient();
}
