// Generated file. DO NOT EDIT MANUALLY.
// Generated by supabase_codegen (4.0.0-alpha.1)

import 'package:supabase/supabase.dart';

/// {@template GetEnumTypesResponse}
/// get_enum_types rpc function response
/// {@endtemplate}
class GetEnumTypesResponse {
  /// {@macro GetEnumTypesResponse}
  GetEnumTypesResponse({required this.enumName, required this.enumValue});

  /// Create [GetEnumTypesResponse] from [json]
  factory GetEnumTypesResponse.fromJson(Map<String, dynamic> json) =>
      GetEnumTypesResponse(
        enumName: json['enum_name'] as String,
        enumValue: json['enum_value'] as String,
      );

  /// Enum Name
  final String enumName;

  /// Enum Value
  final String enumValue;
}

/// RPC extension for get_enum_types rpc
extension GetEnumTypesRpc on SupabaseClient {
  /// Get Enum Types
  Future<List<GetEnumTypesResponse>> getEnumTypes() async {
    final response = await rpc<dynamic>('get_enum_types');

    return (response as List)
        .map((e) => GetEnumTypesResponse.fromJson(e as Map<String, dynamic>))
        .toList();
  }
}
