import 'dart:io';
import 'package:supabase_codegen/src/generator/generator.dart';

/// Date line prefix
const String _dateLinePrefix = '/// Date:';

/// Regex to match the date line
final _dateRegex = RegExp('$_dateLinePrefix .*\n');

/// Write the file header
void writeHeader(StringBuffer buffer) {
  buffer
    ..writeln('//')
    ..writeln('//  Generated file. Do not edit.')
    ..writeln('//  Generated by supabase_codegen ($version)')
    ..writeln('//')
    ..writeln('// ignore_for_file: require_trailing_commas, '
        'constant_identifier_names')
    ..writeln();
}

/// Write the file footer
void writeFooter(StringBuffer buffer) {
  // Write tag
  if (tag.isNotEmpty) {
    buffer.writeln('/// Tag: $tag');
  }

  // Write date
  if (skipFooterWrite) return;

  buffer.writeln('$_dateLinePrefix ${DateTime.now()}');
}

/// Strip the date line from the content for comparison
String _stripDateLine(String content) {
  return content.replaceAll(_dateRegex, '');
}

/// Write the file if the content has changed,
/// ignoring the date line
void writeFileIfChangedIgnoringDate(File file, StringBuffer buffer) {
  final newContent = buffer.toString();
  final newContentStripped = _stripDateLine(newContent);

  if (file.existsSync()) {
    final existingContent = file.readAsStringSync();
    final existingContentStripped = _stripDateLine(existingContent);

    if (newContentStripped != existingContentStripped) {
      file.writeAsStringSync(newContent);
    }
  } else {
    file.writeAsStringSync(newContent);
  }
}
