// Generated file. DO NOT EDIT MANUALLY.
// Generated by supabase_codegen (4.0.0-alpha.1)

export 'add_numbers.dart';
export 'concat_texts.dart';
export 'get_enum_types.dart';
export 'greet_person.dart';
export 'list_users.dart';
export 'process_payload.dart';
export 'reverse_int_array.dart';
export 'store_blob.dart';
export 'sum_array.dart';

// Date: 2025-12-09 14:05:05.178011
