// Generated file. DO NOT EDIT MANUALLY.
// Generated by supabase_codegen (4.0.0-alpha.1)

import 'package:supabase/supabase.dart';

/// RPC extension for add_numbers rpc
extension AddNumbersRpc on SupabaseClient {
  /// Add Numbers
  Future<int> addNumbers({required int a, required int b}) =>
      rpc<int>('add_numbers', params: {'a': a, 'b': b});
}
