// Generated file. DO NOT EDIT MANUALLY.
// Generated by supabase_codegen (4.0.0-alpha.1)

import 'package:supabase_codegen/supabase_codegen.dart';

/// RPC extension for concat_texts rpc
extension ConcatTextsRpc on SupabaseClient {
  /// Concat Texts
  Future<String> concatTexts({required List<String> parts}) =>
      rpc<String>('concat_texts', params: {'parts': parts});
}
