// Generated file. DO NOT EDIT MANUALLY.
// Generated by supabase_codegen (4.0.0-alpha.1)

import 'package:supabase_codegen/supabase_codegen.dart';

/// RPC extension for get_tags rpc
extension GetTagsRpc on SupabaseClient {
  /// Get Tags
  Future<List<String>> getTags({required int entityId}) async {
    final response = await rpc<List<dynamic>>(
      'get_tags',
      params: {'entity_id': entityId},
    );

    return List<String>.from(response);
  }
}
