// Generated file. DO NOT EDIT MANUALLY.
// Generated by supabase_codegen (4.0.0-alpha.1)

import 'package:supabase_codegen/supabase_codegen.dart';

/// {@template GetEnumTypesResponse}
/// get_enum_types rpc function response
/// {@endtemplate}
class GetEnumTypesResponse extends RpcTableResponse {
  /// {@macro GetEnumTypesResponse}
  const GetEnumTypesResponse._(super.json);

  /// Create [GetEnumTypesResponse] from [json]
  factory GetEnumTypesResponse.fromJson(Map<String, dynamic> json) =>
      GetEnumTypesResponse._(json);

  /// Enum Name field name
  static const String enumNameField = 'enum_name';

  /// Enum Name
  String get enumName => raw[enumNameField] as String? ?? '';

  /// Enum Value field name
  static const String enumValueField = 'enum_value';

  /// Enum Value
  String get enumValue => raw[enumValueField] as String? ?? '';

  /// Return String representation of [GetEnumTypesResponse]
  @override
  String toString() {
    return '''
GetEnumTypesResponse(
  $enumNameField: $enumName,
  $enumValueField: $enumValue,
)''';
  }
}

/// RPC extension for get_enum_types rpc
extension GetEnumTypesRpc on SupabaseCodegenFunctions {
  /// Get Enum Types
  Future<List<GetEnumTypesResponse>> getEnumTypes() async {
    final response = await rpc<List<Map<String, dynamic>>>('get_enum_types');

    return response.map(GetEnumTypesResponse.fromJson).toList();
  }
}
