// Generated file. DO NOT EDIT MANUALLY.
// Generated by supabase_codegen (4.0.0-alpha.1)

import 'package:supabase_codegen/supabase_codegen.dart';

/// {@template GetUserSummaryResponse}
/// get_user_summary rpc function response
/// {@endtemplate}
class GetUserSummaryResponse extends RpcTableResponse {
  /// {@macro GetUserSummaryResponse}
  const GetUserSummaryResponse._(super.json);

  /// Create [GetUserSummaryResponse] from [json]
  factory GetUserSummaryResponse.fromJson(Map<String, dynamic> json) =>
      GetUserSummaryResponse._(json);

  /// Email field name
  static const String emailField = 'email';

  /// Email
  String get email => raw[emailField] as String? ?? '';

  /// Login Count field name
  static const String loginCountField = 'login_count';

  /// Login Count
  int get loginCount => raw[loginCountField] as int? ?? 0;

  /// Roles field name
  static const String rolesField = 'roles';

  /// Roles
  List<String> get roles =>
      (raw[rolesField] as List<dynamic>?)?.cast<String>() ?? const [];

  /// Profile field name
  static const String profileField = 'profile';

  /// Profile
  dynamic get profile => raw[profileField];
}

/// RPC extension for get_user_summary rpc
extension GetUserSummaryRpc on SupabaseCodegenFunctions {
  /// Get User Summary
  Future<List<GetUserSummaryResponse>> getUserSummary({
    int? minLogins,
    String? roleFilter,
    int? limitCount,
    int? offsetCount,
  }) async {
    final response = await rpc<List<Map<String, dynamic>>>(
      'get_user_summary',
      params: {
        if (minLogins != null) 'min_logins': minLogins,
        if (roleFilter != null) 'role_filter': roleFilter,
        if (limitCount != null) 'limit_count': limitCount,
        if (offsetCount != null) 'offset_count': offsetCount,
      },
    );

    return response.map(GetUserSummaryResponse.fromJson).toList();
  }
}
