// Generated file. DO NOT EDIT MANUALLY.
// Generated by supabase_codegen (4.0.0-alpha.1)

import 'package:supabase/supabase.dart';

/// RPC extension for greet_person rpc
extension GreetPersonRpc on SupabaseClient {
  /// Greet Person
  Future<String> greetPerson({required dynamic payload}) =>
      rpc<String>('greet_person', params: {'payload': payload});
}
