// Generated file. DO NOT EDIT MANUALLY.
// Generated by supabase_codegen (4.0.0-alpha.1)

import 'package:supabase_codegen/supabase_codegen.dart';
// Relative import of table
// ignore_for_file: relative_imports
import '../tables/users.dart';

/// RPC extension for list_users rpc
extension ListUsersRpc on SupabaseClient {
  /// List Users
  Future<List<UsersRow>> listUsers() async {
    final response = await rpc<List<Map<String, dynamic>>>('list_users');

    return response.map(UsersRow.fromJson).toList();
  }
}
