// Generated file. DO NOT EDIT MANUALLY.
// Generated by supabase_codegen (4.0.0-alpha.1)

import 'package:supabase_codegen/supabase_codegen.dart';

/// RPC extension for process_payload rpc
extension ProcessPayloadRpc on SupabaseCodegenFunctions {
  /// Process Payload
  Future<dynamic> processPayload({required dynamic payload}) =>
      rpc<dynamic>('process_payload', params: {'payload': payload});
}
