// Generated file. DO NOT EDIT MANUALLY.
// Generated by supabase_codegen (4.0.0-alpha.1)

import 'package:supabase_codegen/supabase_codegen.dart';

/// RPC extension for reverse_int_array rpc
extension ReverseIntArrayRpc on SupabaseClient {
  /// Reverse Int Array
  Future<List<int>> reverseIntArray({required List<int> inputArray}) =>
      rpc<List<int>>('reverse_int_array', params: {'input_array': inputArray});
}
