// Generated file. DO NOT EDIT MANUALLY.
// Generated by supabase_codegen (4.0.0-alpha.1)

import 'package:supabase_codegen/supabase_codegen.dart';

/// RPC extension for sum_array rpc
extension SumArrayRpc on SupabaseCodegenFunctions {
  /// Sum Array
  Future<int> sumArray({required List<int> arr}) =>
      rpc<int>('sum_array', params: {'arr': arr});
}
